In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier

In [2]:
def write_answer(file_name, answer):
    with open(f'{file_name}.txt', mode='w') as f:
        f.write(str(answer))

In [3]:
digits = datasets.load_digits()
X = digits.data
Y = digits.target 

## Завдання 1

In [4]:
estimator = DecisionTreeClassifier()

In [5]:
cvs = cross_val_score(estimator, X, Y, cv=10, n_jobs=2)
cvs

array([0.77222222, 0.86666667, 0.82222222, 0.78333333, 0.78888889,
       0.87222222, 0.86666667, 0.83798883, 0.84916201, 0.79329609])

In [6]:
cvs_mean = cvs.mean()
write_answer('answer1', cvs_mean)
cvs_mean

0.8252669149596524

## Завдання 2

In [7]:
bagging = BaggingClassifier(base_estimator=estimator, n_estimators=100)

In [8]:
cvs = cross_val_score(bagging, X, Y, cv=10, n_jobs=2)
cvs

array([0.85      , 0.96666667, 0.9       , 0.91111111, 0.93333333,
       0.98888889, 0.96666667, 0.91061453, 0.87150838, 0.91061453])

In [9]:
cvs_mean = cvs.mean()
write_answer('answer2', cvs_mean)
cvs_mean

0.9209404096834264

## Завдання 3

In [10]:
bagging = BaggingClassifier(base_estimator=estimator, n_estimators=100,
                           max_features=int(np.sqrt(X.shape[1])))

In [11]:
cvs = cross_val_score(bagging, X, Y, cv=10, n_jobs=2)
cvs

array([0.89444444, 0.95555556, 0.94444444, 0.88888889, 0.95555556,
       0.92777778, 0.97777778, 0.98882682, 0.89385475, 0.89944134])

In [12]:
cvs_mean = cvs.mean()
write_answer('answer3', cvs_mean)
cvs_mean

0.9326567349472377

## Завдання 4

In [13]:
estimator = DecisionTreeClassifier(max_features='sqrt')

In [14]:
bagging = BaggingClassifier(base_estimator=estimator, n_estimators=100)

In [15]:
cvs = cross_val_score(bagging, X, Y, cv=10, n_jobs=2)
cvs

array([0.89444444, 0.97222222, 0.93333333, 0.91666667, 0.96111111,
       0.97777778, 0.97777778, 0.96089385, 0.91620112, 0.93854749])

In [16]:
cvs_mean = cvs.mean()
write_answer('answer4', cvs_mean)
cvs_mean

0.9448975791433891

## Завдання 5

In [17]:
clf = RandomForestClassifier(max_features='sqrt')

In [18]:
cvs = cross_val_score(clf, X, Y, cv=10, n_jobs=2)
cvs

array([0.89444444, 0.97777778, 0.93888889, 0.93333333, 0.96666667,
       0.97222222, 0.97222222, 0.96648045, 0.93296089, 0.94413408])

In [19]:
cvs_mean = cvs.mean()
cvs_mean

0.9499130974549969

In [20]:
write_answer('answer5', "2 3 4 7")